"""
This script performs hierarchical clustering on embeddings generated by multiple GPUs.
It follows the UNICOM approach and is intended to work with SLURM, where each GPU generates a set of centroids and then
aggregates them to form a global set of centroids. The final clustering is performed
to reduce the number of centroids to a specified number.

See this comment for more details: https://github.com/deepglint/unicom/issues/20#issuecomment-2081351831
"""

import os
import torch
import torch.distributed as dist
import numpy as np
from scipy.io import savemat, loadmat
import faiss
import faiss.contrib.torch_utils
from pathlib import Path
import argparse
import logging


# [Previous setup_logging and setup_distributed functions remain the same]
def setup_logging(rank):
    logging.basicConfig(
        level=logging.INFO,
        format=f"[Rank {rank}] %(asctime)s - %(levelname)s - %(message)s",
        handlers=[
            logging.FileHandler(f"clustering_rank_{rank}.log"),
            logging.StreamHandler(),
        ],
    )


def setup_distributed():
    rank = int(os.environ["SLURM_PROCID"])
    world_size = int(os.environ["SLURM_NTASKS"])
    local_rank = int(os.environ["SLURM_LOCALID"])

    # master_addr = os.environ["SLURM_SUBMIT_HOST"] # Don't use SUBMIT HOST, it's the login node at UFL HiPerGator
    # Get the first node in the allocation for the master address
    master_addr = os.environ["SLURM_NODELIST"].split(",")[0].split("[")[0]
    master_port = int(os.environ.get("MASTER_PORT", "12355"))

    os.environ["MASTER_ADDR"] = master_addr
    os.environ["MASTER_PORT"] = str(master_port)

    dist.init_process_group("nccl", rank=rank, world_size=world_size)
    torch.cuda.set_device(local_rank)

    setup_logging(rank)
    logging.info(
        f"Initialized distributed process: rank {rank}/{world_size} on {master_addr}"
    )

    return rank, world_size, local_rank


def perform_local_clustering(embeddings, d, local_rank, target_centroids=1000000):
    """
    Perform local clustering on each GPU to produce target_centroids centroids.

    Args:
        embeddings (np.ndarray): The input embeddings to cluster.
        d (int): The dimensionality of the embeddings.
        local_rank (int): The rank of the local GPU.
        target_centroids (int, optional): The number of centroids to generate. Defaults to 1000000.

    Returns:
        np.ndarray: The centroids generated from the local clustering.
    """
    logging.info(
        f"Performing local clustering to generate {target_centroids} centroids"
    )

    res = faiss.StandardGpuResources()
    cfg = faiss.GpuIndexFlatConfig()
    cfg.device = local_rank

    kmeans = faiss.GpuKmeans(d, target_centroids, cfg, res)
    kmeans.train(embeddings)

    return kmeans.centroids


def perform_final_clustering(all_centroids, d, local_rank, final_centroids=1000000):
    """
    Perform final clustering on the combined centroids from all GPUs.

    Args:
        all_centroids (np.ndarray): The combined centroids from all GPUs.
        d (int): The dimensionality of the centroids.
        local_rank (int): The rank of the local GPU.
        final_centroids (int, optional): The number of final centroids to generate. Defaults to 1000000.

    Returns:
        np.ndarray: The final centroids after clustering.
    """
    logging.info(
        f"Performing final clustering to reduce to {final_centroids} centroids"
    )

    res = faiss.StandardGpuResources()
    cfg = faiss.GpuIndexFlatConfig()
    cfg.device = local_rank

    final_kmeans = faiss.GpuKmeans(d, final_centroids, cfg, res)
    final_kmeans.train(all_centroids)

    return final_kmeans.centroids


def main(args):
    """
    Main function to execute the clustering process.

    Args:
        args (Namespace): The command line arguments parsed from the input.
    """
    rank, world_size, local_rank = setup_distributed()

    try:
        # Load embeddings with the same directory structure as before
        embeddings_base_dir = (
            Path(args.embeddings_dir) / f"embeddings_{args.cohort}_{args.model_name}"
        )
        node_rank_dirs = list(embeddings_base_dir.glob("*_*"))

        logging.info(f"Found {len(node_rank_dirs)} node_rank directories")

        # Load embeddings for this GPU
        all_embeddings = []
        metadata = []

        for node_rank_dir in node_rank_dirs:
            logging.info(f"Processing directory: {node_rank_dir}")
            mat_files = sorted(list(node_rank_dir.glob("batch_*.mat")))

            for mat_file in mat_files:
                data = loadmat(mat_file)
                image_emb = data["image_embeddings"]
                text_emb = data["text_embeddings"]
                joint_emb = (image_emb + text_emb) / 2
                all_embeddings.extend(joint_emb)

                metadata.extend(
                    [
                        {"image_path": p, "scientific_name": s, "category": c}
                        for p, s, c in zip(
                            data["image_paths"],
                            data["scientific_names"],
                            data["categories"],
                        )
                    ]
                )

        embeddings = np.array(all_embeddings, dtype=np.float32)
        d = embeddings.shape[1]
        logging.info(f"Loaded {len(embeddings)} embeddings")

        # First stage: Each GPU creates 1M centroids (like UNICOM)
        local_centroids = perform_local_clustering(
            embeddings, d, local_rank, target_centroids=args.local_centroids
        )

        # Gather all centroids on rank 0
        gathered_centroids = [
            torch.zeros_like(torch.from_numpy(local_centroids))
            for _ in range(world_size)
        ]
        dist.all_gather(gathered_centroids, torch.from_numpy(local_centroids))

        if rank == 0:
            # Combine all local centroids
            all_centroids = np.concatenate([c.numpy() for c in gathered_centroids])
            logging.info(f"Combined {len(all_centroids)} centroids from all GPUs")

            # Second stage: Cluster down to final number of centroids
            final_centroids = perform_final_clustering(
                all_centroids, d, local_rank, final_centroids=args.n_clusters
            )

            # Save results
            output_dir = (
                Path(args.output_dir) / f"clustering_{args.cohort}_{args.model_name}"
            )
            output_dir.mkdir(parents=True, exist_ok=True)

            save_path = output_dir / "final_centroids.mat"
            save_dict = {
                "centroids": final_centroids,
                "n_clusters": args.n_clusters,
                "model_name": args.model_name,
                "cohort": args.cohort,
                "local_centroids_per_gpu": args.local_centroids,
                "total_gpus": world_size,
            }
            savemat(save_path, save_dict)
            logging.info(f"Saved final centroids to {save_path}")

        dist.barrier()
        logging.info("Clustering completed successfully")

    except Exception as e:
        logging.error(f"Error in perform_clustering: {e}")
        raise


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--embeddings_dir",
        type=str,
        required=True,
        help="Base directory containing the embedding directories",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        required=True,
        help="Directory to save the final clustering results",
    )
    parser.add_argument(
        "--model_name",
        type=str,
        default="ViT-H-14-378-quickgelu",
        help="Model name used for embedding generation",
    )
    parser.add_argument(
        "--cohort", type=str, default="train", help="Dataset cohort (train/test)"
    )
    parser.add_argument(
        "--n_clusters",
        type=int,
        default=1000000,
        help="Number of clusters for final clustering",
    )
    parser.add_argument(
        "--local_centroids",
        type=int,
        default=1000000,
        help="Number of centroids each GPU should generate (UNICOM used 1M)",
    )

    args = parser.parse_args()
    main(args)
