"""
This script performs hierarchical clustering on embeddings generated by multiple GPUs.
It follows the UNICOM approach and is intended to work with SLURM, where each GPU generates a set of centroids and then
aggregates them to form a global set of centroids. The final clustering is performed
to reduce the number of centroids to a specified number.
"""

import os
import torch
import torch.distributed as dist
import numpy as np
from scipy.io import savemat, loadmat
import faiss
import pandas as pd
import faiss.contrib.torch_utils
from pathlib import Path
import argparse
import logging


def setup_logging(rank):
    log_file = f"clustering_rank_{rank}.log"

    logging.basicConfig(
        level=logging.INFO,
        format=f"[Rank {rank}] %(asctime)s - %(levelname)s - %(message)s",
        handlers=[
            logging.FileHandler(log_file),
            logging.StreamHandler(),
        ],
    )
    logging.info(f"Logging initialized for rank {rank}. Log file: {log_file}")


def setup_distributed():
    rank = int(os.environ["SLURM_PROCID"])
    world_size = int(os.environ["SLURM_NTASKS"])
    local_rank = int(os.environ["SLURM_LOCALID"])

    # Get the hostname of the first node
    nodes = os.environ["SLURM_NODELIST"]
    if "[" in nodes:
        # Handle node ranges like "c0800a-s[11,17,23]"
        prefix = nodes.split("[")[0]
        node_nums = nodes.split("[")[1].split("]")[0].split(",")
        master_addr = f"{prefix}{node_nums[0]}"
    else:
        # Handle single node or comma-separated list
        master_addr = nodes.split(",")[0]

    master_port = int(os.environ.get("MASTER_PORT", "12355"))

    logging.info(f"Using master node: {master_addr}")
    os.environ["MASTER_ADDR"] = master_addr
    os.environ["MASTER_PORT"] = str(master_port)

    # Add some debugging info
    logging.info(f"SLURM_NODELIST: {os.environ['SLURM_NODELIST']}")
    logging.info(f"SLURM_PROCID: {rank}")
    logging.info(f"MASTER_ADDR: {master_addr}")
    logging.info(f"MASTER_PORT: {master_port}")

    dist.init_process_group("nccl", rank=rank, world_size=world_size)
    torch.cuda.set_device(local_rank)

    return rank, world_size, local_rank


def perform_local_clustering(embeddings, d, local_rank, target_centroids=1000000):
    """
    Perform local clustering on each GPU to produce target_centroids centroids.
    """
    logging.info(
        f"Starting local clustering on rank {local_rank} for {len(embeddings)} embeddings"
    )
    try:
        kmeans = faiss.Kmeans(
            d,  # dimension
            target_centroids,  # number of centroids
            niter=20,  # number of iterations
            verbose=True,  # verbose output
            gpu=True,  # use GPU
            nredo=1,  # number of clustering runs to perform
            spherical=False,  # do not normalize centroids
        )

        kmeans.train(embeddings)

        logging.info(f"Completed local clustering with {target_centroids} centroids")
        return kmeans.centroids

    except Exception as e:
        logging.error(f"Error in local clustering: {e}")
        raise


def perform_final_clustering(all_centroids, d, local_rank, final_centroids=1000000):
    """
    Perform final clustering on the combined centroids from all GPUs.
    """
    logging.info(f"Starting final clustering to reduce to {final_centroids} centroids")
    try:
        kmeans = faiss.Kmeans(
            d,  # dimension
            final_centroids,  # number of centroids
            niter=20,  # number of iterations
            verbose=True,  # verbose output
            gpu=True,  # use GPU
            nredo=1,  # number of clustering runs to perform
            spherical=False,  # do not normalize centroids
        )

        kmeans.train(all_centroids)

        logging.info("Completed final clustering")
        return kmeans.centroids

    except Exception as e:
        logging.error(f"Error in final clustering: {e}")
        raise


def main(args):
    """
    Main function to execute the clustering process.
    """
    # Set up logging first
    rank = int(os.environ["SLURM_PROCID"])
    setup_logging(rank)

    # Then set up distributed
    rank, world_size, local_rank = setup_distributed()

    try:
        # Load embeddings with the same directory structure as before
        embeddings_base_dir = (
            Path(args.embeddings_dir) / f"embeddings_{args.cohort}_{args.model_name}"
        )
        node_rank_dirs = list(embeddings_base_dir.glob("*_*"))

        logging.info(f"Found {len(node_rank_dirs)} node_rank directories")

        # Load embeddings for this GPU
        all_embeddings = []

        for node_rank_dir in node_rank_dirs:
            logging.info(f"Processing directory: {node_rank_dir}")
            mat_files = sorted(list(node_rank_dir.glob("batch_*.mat")))

            for i, mat_file in enumerate(mat_files):
                if i % 10 == 0:  # Log every 10 batches
                    logging.info(f"Loading batch {i}/{len(mat_files)}")

                data = loadmat(mat_file)
                image_emb = data["image_embeddings"]
                text_emb = data["text_embeddings"]
                joint_emb = (image_emb + text_emb) / 2
                all_embeddings.extend(joint_emb)

        embeddings = np.array(all_embeddings, dtype=np.float32)
        d = embeddings.shape[1]
        logging.info(f"Loaded {len(embeddings)} embeddings")

        # First stage: Each GPU creates local centroids
        local_centroids = perform_local_clustering(
            embeddings, d, local_rank, target_centroids=args.local_centroids
        )

        # Clean up embeddings
        del embeddings
        torch.cuda.empty_cache()

        # Gather all centroids on rank 0
        local_centroids_tensor = torch.from_numpy(local_centroids).to(local_rank)
        gathered_centroids = [
            torch.zeros_like(local_centroids_tensor, device=local_rank)
            for _ in range(world_size)
        ]
        dist.all_gather(gathered_centroids, local_centroids_tensor)

        if rank == 0:
            # Combine all local centroids
            all_centroids = np.concatenate(
                [c.cpu().numpy() for c in gathered_centroids]
            )
            logging.info(f"Combined {len(all_centroids)} centroids from all GPUs")

            # Clean up gathered centroids
            del gathered_centroids
            torch.cuda.empty_cache()

            # Second stage: Cluster down to final number of centroids
            final_centroids = perform_final_clustering(
                all_centroids, d, local_rank, final_centroids=args.n_clusters
            )
            logging.info(f"Completed final clustering to {args.n_clusters} centroids")

            # After getting final centroids, load original embeddings again for assignment
            logging.info("Loading original embeddings for cluster assignment...")

            all_image_embeddings = []
            all_image_paths = []
            all_scientific_names = []

            embeddings_base_dir = (
                Path(args.embeddings_dir)
                / f"embeddings_{args.cohort}_{args.model_name}"
            )
            node_rank_dirs = list(embeddings_base_dir.glob("*_*"))

            # Load all original embeddings and metadata
            for node_rank_dir in node_rank_dirs:
                mat_files = sorted(list(node_rank_dir.glob("batch_*.mat")))
                for i, mat_file in enumerate(mat_files):
                    if i % 10 == 0:
                        logging.info(f"Loading batch {i}/{len(mat_files)}")

                    data = loadmat(mat_file)
                    image_emb = data["image_embeddings"]
                    text_emb = data["text_embeddings"]
                    joint_emb = (image_emb + text_emb) / 2
                    all_image_embeddings.extend(joint_emb)

                    # Store metadata
                    all_image_paths.extend(
                        [str(p).strip() for p in data["image_paths"]]
                    )
                    all_scientific_names.extend(
                        [str(s).strip() for s in data["scientific_names"]]
                    )

            # Convert to numpy arrays
            joint_embeddings = np.array(all_image_embeddings, dtype=np.float32)

            # Create index for final centroids and add them
            d = joint_embeddings.shape[1]
            index = faiss.IndexFlatL2(d)
            index.add(final_centroids)

            # Search for nearest centroids
            logging.info("Assigning embeddings to clusters...")
            D, I = index.search(
                joint_embeddings, 1
            )  # get nearest centroid for each embedding

            # Before creating the DataFrame, add debugging logs
            logging.info(f"Length of all_image_paths: {len(all_image_paths)}")
            logging.info(f"Length of all_scientific_names: {len(all_scientific_names)}")
            logging.info(f"Length of cluster_ids: {len(I.flatten())}")
            logging.info(f"Length of distances: {len(D.flatten())}")

            # Create results DataFrame
            results_df = pd.DataFrame(
                {
                    "image_path": all_image_paths,
                    "scientific_name": all_scientific_names,
                    "cluster_id": I.flatten(),
                    "distance_to_centroid": D.flatten(),
                }
            )

            # Save results
            output_dir = (
                Path(args.output_dir) / f"clustering_{args.cohort}_{args.model_name}"
            )
            output_dir.mkdir(parents=True, exist_ok=True)

            # Save DataFrame as CSV
            csv_path = output_dir / f"cluster_assignments.csv"
            results_df.to_csv(csv_path, index=False)
            logging.info(f"Saved cluster assignments to {csv_path}")

            # Save complete results as mat file
            mat_path = output_dir / "final_clustering_results.mat"
            save_dict = {
                "centroids": final_centroids,
                "cluster_ids": I.flatten(),
                "distances": D.flatten(),
                "image_paths": np.array(all_image_paths),
                "scientific_names": np.array(all_scientific_names),
                "n_clusters": args.n_clusters,
                "model_name": args.model_name,
                "cohort": args.cohort,
                "local_centroids_per_gpu": args.local_centroids,
                "total_gpus": world_size,
            }
            savemat(mat_path, save_dict)
            logging.info(f"Saved complete results to {mat_path}")

        dist.barrier()
        logging.info("Clustering and assignment completed successfully")

    except Exception as e:
        logging.error(f"Error in perform_clustering: {e}")
        raise


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--embeddings_dir",
        type=str,
        required=True,
        help="Base directory containing the embedding directories",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        required=True,
        help="Directory to save the final clustering results",
    )
    parser.add_argument(
        "--model_name",
        type=str,
        default="ViT-H-14-378-quickgelu",
        help="Model name used for embedding generation",
    )
    parser.add_argument(
        "--cohort", type=str, default="train", help="Dataset cohort (train/test)"
    )
    parser.add_argument(
        "--n_clusters",
        type=int,
        default=1000000,
        help="Number of clusters for final clustering",
    )
    parser.add_argument(
        "--local_centroids",
        type=int,
        default=1000000,
        help="Number of centroids each GPU should generate (UNICOM used 1M)",
    )

    args = parser.parse_args()
    main(args)
