services:
  python-app:
    build:
      context: ../..
      dockerfile: .devcontainer/backend/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    networks:
      - default
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    ports:
      - 45679:45679
    depends_on:
      - redis
      - postgres

  redis:
    image: redis/redis-stack:7.2.0-v10
    restart: unless-stopped
    networks:
      - default
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
      - 8001:8001

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - default
    volumes:
      - mongo-data:/data

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8082:8081
    networks:
      - default
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  postgres:
    image: postgres:16
    restart: unless-stopped
    networks:
      - default
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
  redis-data:
  mongo-data:
