services:
  python-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    networks:
      - default
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    ports:
      - 45679:45679
    depends_on:
    - redis
    - postgres
    - mongo

  redis:
    image: redis/redis-stack:7.2.0-v10
    restart: unless-stopped
    networks:
      - default
    volumes:
      - redis-data:/data/redis
    ports:
      - 6379:6379
      - 8001:8001

  postgres:
    image: postgres:16
    restart: unless-stopped
    networks:
      - default
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  mongo:
    image: mongo:latest
    restart: unless-stopped
    networks:
    - default
    volumes:
      - mongodb-data:/data/mongo
    ports:
    - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_DATABASE: local

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME:
      ME_CONFIG_MONGODB_ADMINPASSWORD:
      ME_CONFIG_MONGODB_URL: mongodb://:@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  postgres-data:
  redis-data:
  mongodb-data:
